#!/bin/bash

set -eo pipefail

PYTHON_INTERPRETER_PATH=@PYTHON_INTERPRETER_PATH@
if [ ! -z "$PYTHON_INTERPRETER_PATH" ]; then
    export PATH="$PYTHON_INTERPRETER_PATH:$PATH"
    export PYTHONHOME="$(dirname $PYTHON_INTERPRETER_PATH)/.."
    export PYTHONPATH="$PWD:@PYTHONPATH@"
fi

export LD_LIBRARY_PATH="@LD_LIBRARY_PATH@"

exec @APP@ "$@"
